#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
markdown_editor.ui.__init__
===========================

This contains wrapper classes for all the ui modules

This file is maintained as shorthand and to prevent overwriting
the pyside generated files that contain the meat on the bones of
the controls themselves
"""
from __future__ import absolute_import, unicode_literals

from .editor import Ui_MainWindow
from PySide import QtGui as gui

from markdown2 import Markdown


class ControlMainWindow(gui.QMainWindow):
    """
    This is the main window class. Called as the first window shown.

    Creates and runs UI_MainWindow from the autogenerated editor modules
    """
    def __init__(self, parent=None):
        super(ControlMainWindow, self).__init__(parent)
        self.markdown = Markdown()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.ui.txtInput.textChanged.connect(self.text_changed)

    def text_changed(self):
        raw = self.ui.txtInput.toPlainText()
        md = self.markdown.convert(raw)
        self.ui.txtOutput.setHtml(md)
